#!/bin/sh

export PATH="$PATH:$(find ~/.local/bin -type d | paste -sd ':' -)"
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:$HOME/.dotnet/tools"

export PYTHONPATH="$HOME/.local/lib/python:$PYTHONPATH"

export EDITOR="nvim"
export TERMINAL="kitty"
export TERMINAL_PROG="kitty"
export PAGER="nvimpager_wrapper"
export GIT_PAGER="nvimpager_wrapper"
export MANPAGER="nvimpager_wrapper"

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"
export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"
export NOTMUCH_CONFIG="$XDG_CONFIG_HOME/notmuch-config"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export INPUTRC="$XDG_CONFIG_HOME/shell/inputrc"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export WINEPREFIX="$XDG_DATA_HOME/wineprefixes/default"
export KODI_DATA="$XDG_DATA_HOME/kodi"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export ANDROID_SDK_HOME="$XDG_CONFIG_HOME/android"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export CP_HOME_DIR="$XDG_DATA_HOME/cocoapods"
export PERL_CPANM_HOME="$XDG_CACHE_HOME/cpanm"
export DOTNET_CLI_HOME="$XDG_DATA_HOME/dotnet"
export GOPATH="$XDG_DATA_HOME/go"
export GOMODCACHE="$XDG_CACHE_HOME/go/mod"
export GRADLE_USER_HOME="$XDG_DATA_HOME/gradle"
export ANSIBLE_CONFIG="$XDG_CONFIG_HOME/ansible/ansible.cfg"
export UNISON="$XDG_DATA_HOME/unison"
export HISTFILE="$XDG_DATA_HOME/history"
export MBSYNCRC="$XDG_CONFIG_HOME/mbsync/config"
export ELECTRUMDIR="$XDG_DATA_HOME/electrum"
export SQLITE_HISTORY="$XDG_DATA_HOME/sqlite_history"
export LESSHISTFILE="-"
export COMPOSER_HOME="$XDG_CONFIG_HOME/composer"
export SCREENRC="$XDG_CONFIG_HOME/screen/screenrc"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export TERMINFO="$XDG_DATA_HOME/terminfo"
export TERMINFO_DIRS="$XDG_DATA_HOME/terminfo:/usr/share/terminfo"
export NODE_REPL_HISTORY="$XDG_STATE_HOME/node_repl_history"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npmrc"
export NPM_CONFIG_INIT_MODULE="$XDG_CONFIG_HOME/npm/config/npm-init.js"
export NPM_CONFIG_CACHE="$XDG_CACHE_HOME/npm"
export NPM_CONFIG_TMP="$XDG_RUNTIME_DIR/npm"
export NUGET_PACKAGES="$XDG_CACHE_HOME/NuGetPackages"
export OMNISHARPHOME="$XDG_CONFIG_HOME/omnisharp"
export PYTHON_HISTORY="$XDG_DATA_HOME/python_history"
export TLDR_CACHE_DIR="$XDG_CACHE_HOME/tldr"
export TS_NODE_HISTORY="$XDG_STATE_HOME/ts_node_repl_history"
export W3M_DIR="$XDG_DATA_HOME/w3m"

# export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker
# export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc"

export JAVA_HOME="/Library/Java/JavaVirtualMachines/openjdk.jdk/Contents/Home/"
export FrameworkPathOverride="/opt/homebrew/bin/mono"

export HOMEBREW_NO_EMOJI=1
export HOMEBREW_NO_ENV_HINTS=1
export SHELL_SESSIONS_DISABLE=1
export DOCKER_CLI_HINTS=false

eval "$(/opt/homebrew/bin/brew shellenv)"
